### ISSUE TITLE
Running script error

### ISSUE THREAD

**Issue by Timileyin105** [alvaroBegnini/bot-manager-telegram#1]
Hello 👋, I am Timi, 
i had error runnning the script 
importing the module this way gives error   **import TelegramBot from "telegram-bot-nodejs"**
so i later use this method to import then  works ** require( "telegram-bot-nodejs" ) **
but after the error went off the next error was  **TelegramBot is not a constructor** 
can you please help out on this

**Comment by Timileyin105** [comment]
hello i changed the package export type and worked for node js with no issue\

**Comment by alvaroBegnini** [comment]
Hello Timi  👋! 

A new release of this project is now available and this problem is currently fixed
Thanks for your support.


I think that the problem with "import TelegramBot from "telegram-bot-nodejs" that you mentioned can be fixed by adding this line to your package.json
```ts
"type": "module", 
```


but i'll add the require method to the documentation anyways.

*have a great day*

**Comment by Timileyin105** [comment]
ok good, i would like to know if possible to send clickable buttons options to users instead of text and how to get callback on those button click

**Comment by alvaroBegnini** [comment]
Currently this is not possible but i'm working on it and plan to release a new version in the next few weeks.
